## First Numpy

In [ ]:
#python list 
#numpy c++ array-->continuous 1 2 3
#discrete fourier transform,linear algebra,basic statistical 
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
print(type(arr))
print(arr)
print(arr[1])
print(arr.ndim)

## ndim

In [ ]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr1)
print(arr1.ndim)#row , col 2D array

## 3D

In [22]:
arr2 = np.arange(8)# 0 to 7
print(arr2)
print(arr2.ndim)

#2D
arr2D = arr2.reshape(2,4)#row col
print(arr2D)
print(arr2D.ndim)

#3D
arr3D = arr2.reshape(2,2,2)#last 2 ---> 2depth
print(arr3D)
print(arr3D.ndim)

[0 1 2 3 4 5 6 7]
1
[[0 1 2 3]
 [4 5 6 7]]
2
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


## asArray

In [31]:
arrAsArray  = np.zeros((3,3),dtype=int)#default C
print(arrAsArray)

arrAsArray1  = np.ones((3,3),dtype=float)#default C
print(arrAsArray1)

myList = (1,2,3,4,5,6,7,8,9)
print(type(myList))
npArray = np.asarray(myList)
print(npArray)
print(type(npArray))

#asarray -- routine
#shape , type , C 
#C ---> contiguous layout(row major-order) default
#F ----> fortran layour(col major-order)
#A --> Any Order
#K --> Keep order

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'tuple'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## markdown

<img src="image.png">

<video controls src="video_sample.avi">My Video</video>

## FromBuffer

In [39]:
#buffer data
#FromBuffer ---> 4 parameters
#data(bdata),data type,count,offset
bufferData = b'nationalcybercityi'
print(type(bufferData))#bytes

#nparray = np.frombuffer(bufferData,dtype='S1',count=-1,offset=0)
nparray = np.frombuffer(bufferData,dtype='S2',count=9,offset=0)
print(nparray)
print(type(nparray))
#String of length S1 = 1


<class 'bytes'>
[b'na' b'ti' b'on' b'al' b'cy' b'be' b'rc' b'it' b'yi']
<class 'numpy.ndarray'>


## FromIter

In [50]:
#fromiter
myDList = [1,2,3,4,5,6]
arr = np.fromiter(myDList,dtype= float)#2 parameters --> iterable,dtype
print(arr)
print(type(arr))

#int data handle
arrObj = np.arange(0,20,3)
print(arrObj)

#linspace non-integer value
arrObj1 = np.linspace(0,20,3)#last count
print(arrObj1)


arrObj2 = np.linspace(0,20,1000)#last count
print(arrObj2)

[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
[ 0  3  6  9 12 15 18]
[ 0. 10. 20.]
[ 0.          0.02002002  0.04004004  0.06006006  0.08008008  0.1001001
  0.12012012  0.14014014  0.16016016  0.18018018  0.2002002   0.22022022
  0.24024024  0.26026026  0.28028028  0.3003003   0.32032032  0.34034034
  0.36036036  0.38038038  0.4004004   0.42042042  0.44044044  0.46046046
  0.48048048  0.5005005   0.52052052  0.54054054  0.56056056  0.58058058
  0.6006006   0.62062062  0.64064064  0.66066066  0.68068068  0.7007007
  0.72072072  0.74074074  0.76076076  0.78078078  0.8008008   0.82082082
  0.84084084  0.86086086  0.88088088  0.9009009   0.92092092  0.94094094
  0.96096096  0.98098098  1.001001    1.02102102  1.04104104  1.06106106
  1.08108108  1.1011011   1.12112112  1.14114114  1.16116116  1.18118118
  1.2012012   1.22122122  1.24124124  1.26126126  1.28128128  1.3013013
  1.32132132  1.34134134  1.36136136  1.38138138  1.4014014   1.42142142
  1.44144144  1.46146146  1.48148148  1.501501