## Logarithmic Sequence

In [5]:
import numpy as np
arrObj = np.logspace(0,2,6)#10 power 0,10 power 2---> 5 number
print(arrObj)

[  1.           2.51188643   6.30957344  15.84893192  39.81071706
 100.        ]


## Mesh Grid

In [14]:
#1 dimensional array to multi dimensional array --> convert
x = np.array([-1,0,1])
y = np.array([-2,0,2])
print(x)
print(y)
X,Y = np.meshgrid(x,y)
print(X)#row
print(X.ndim)
print(X.shape)
print(Y)#col
print(Y.ndim)
print(Y.shape)

z = X + Y
print(z)

s = (X*Y)
print(s)


[-1  0  1]
[-2  0  2]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
2
(3, 3)
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
2
(3, 3)
[[-3 -2 -1]
 [-1  0  1]
 [ 1  2  3]]
[[ 2  0 -2]
 [ 0  0  0]
 [-2  0  2]]


## Matrix Properties

In [42]:
#full_like  ---> clone
x = np.array([-1,0,1])
y = np.array([-2,0,2])
X,Y = np.meshgrid(x,y)
print(X)
print(X.shape)
def full(inarray):
    newarr = np.full_like(inarray,11)
    return newarr
fullX = full(X)
print(fullX)
fullX.shape

#Identity 
idenArray = np.identity(4)
idenArray1 = np.identity(2,dtype='int')
print(idenArray)
print(idenArray1)

#eye
eyeArray = np.eye(6,k=0)#k =index
print(eyeArray)

#Custom diagonal
x = np.arange(1,20,5)
x
diArray = np.diag(x)
diArray

diArray1 = np.diag(x,k=11)
diArray1#row col extend


diArray2 = np.diag(x,k=-1)
diArray2#row col extend

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
(3, 3)
[[11 11 11]
 [11 11 11]
 [11 11 11]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0]
 [0 1]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


array([[ 0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 11,  0,  0],
       [ 0,  0,  0, 16,  0]])

## Slicing And Indexing

In [51]:
arr = np.arange(0,10)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[1:-1])
print(arr[1:-1:2])
print(arr[:5])
print(arr[-2:])
print(arr[::-2])#reverse

[0 1 2 3 4 5 6 7 8 9]
0
9
[1 2 3 4 5 6 7 8]
[1 3 5 7]
[0 1 2 3 4]
[8 9]
[9 7 5 3 1]


## Flatten And NewAxis

In [76]:
data = np.array([[1,2,3],[4,5,6]])
data.ndim
data.shape

#to flaten
flat = data.flatten()
print(flat)
flat.shape  #(6,)
flat.ndim

#new Axis
row_vec = flat[np.newaxis,:]#[row,col]
print("Row Vector: ",row_vec)
print(row_vec.shape)
col_vec = flat[:,np.newaxis]
print(col_vec)
print(col_vec.shape)

z = row_vec + col_vec
print(z)
print(z.shape)

[1 2 3 4 5 6]
Row Vector:  [[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]
(6, 6)


## expand_dim,vstack,hstack

In [85]:
#expand_dims
arr = np.arange(5)
print(arr)
col_exp = np.expand_dims(arr,axis=1)
#1 col vec style
print(col_exp)
print(col_exp.shape)

row_exp = np.expand_dims(arr,axis=0)
print(row_exp)
print(row_exp.shape)

#vstack
#vertical or row 
vs = np.vstack((arr,arr,arr))
print(vs)
print(vs.shape)

#hstack or col
hs = np.hstack((arr,arr,arr))
print(hs)
print(hs.shape)


[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)
[[0 1 2 3 4]]
(1, 5)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
(3, 5)
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
(15,)


## Recap

In [123]:
arr = np.array([
    [1,2,3],[4,5,6],[7,8,9]
],dtype= float)
print(arr)
print(arr.ndim)
print(arr.shape)

#Zeros
numZeros = np.zeros((3,3),dtype = 'int32')#default float64
print(numZeros)
print(numZeros.dtype)
print(numZeros.itemsize)#bytes
print(numZeros.nbytes)#get total size

#accessing
print(arr[2][2])
#startindex:endindex:stepsize for one D

#3D 
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b.ndim)
print(b.shape)#depth 2 ---> 3D
print(b[0,1,0])#work outside in
print(b[1,1,1])#8

b[1,1,1] = 88
print(b)


#All one
np.ones(5)
np.ones((2,3))


#any other number
np.full((2,2),99,dtype=float)

#full_like
c= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
print(c.shape)
d = np.full_like(c,4)
print(d)
print(d.shape)



[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2
(3, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
4
36
9.0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
3
8
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7 88]]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
(2, 7)


In [127]:
#math
a = np.array([1,2,3,4])
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [133]:
a = np.ones((2,3))
a

b = np.full((3,2),2)
b

#use matmul
np.matmul(a,b)

#find determinant
c = np.identity(3)
c
np.linalg.det(c)

#futher info --> https://numpy.org/doc/stable/reference/routines.linalg.html

1.0

## Statistics

In [145]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
np.max(stats)
np.max(stats,axis=1)#row
np.max(stats,axis=0)#col

np.sum(stats,axis=1)#row
np.sum(stats,axis=0)#col

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

## Load Data

In [148]:
filedata = np.genfromtxt('data.txt',delimiter=',')
print(filedata)

filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Multiply Two Matrices

In [150]:
matrix1 = [
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
]


matrix2 = [
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
]
#2*3 3*2 = 2*2
result  = np.dot(matrix1,matrix2)
print(result)

#For Practice ---> https://www.w3resource.com/python-exercises/numpy/index.php

[[19 67 63]
 [25 84 97]
 [20 75 95]]


## Assignment

*Checkboard Pattern* 

<img src="assignment.png">